# Generated by Django 5.2.4 on 2026-10-10 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0002_institute_profile_split'),
        ('training', '0002_module_outcome_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.CharField(blank=True, max_length=2000)),
                ('type', models.CharField(choices=[('ENQUIRY', 'Enquiry'), ('INTEREST', 'Interest')], default='ENQUIRY', max_length=10)),
                ('preferred_time', models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('DAY', 'Day'), ('EVENING', 'Evening'), ('WEEKEND', 'Weekend')], max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('FOLLOW_UP', 'Follow-up'), ('INTERESTED', 'Interested'), ('CONVERTED', 'Converted'), ('NOT_INTERESTED', 'Not interested'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('device_token', models.UUIDField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='institutes.institute')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='training.training')),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=2000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='enquiries.enquiry')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['institute', 'status', '-created_at'], name='enquiry_inst_status_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['device_token', '-created_at'], name='enquiry_device_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['training', 'status'], name='enquiry_training_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='enquiry',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('NEW', 'CONTACTED', 'FOLLOW_UP', 'INTERESTED', 'CONVERTED', 'NOT_INTERESTED', 'CLOSED'))), name='enquiry_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='enquiry',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ('ENQUIRY', 'INTEREST'))), name='enquiry_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='enquiry',
            constraint=models.CheckConstraint(condition=models.Q(('preferred_time', ''), ('preferred_time__in', ('MORNING', 'DAY', 'EVENING', 'WEEKEND')), _connector='OR'), name='enquiry_preferred_time_valid'),
        ),
        migrations.AddConstraint(
            model_name='enquiry',
            constraint=models.CheckConstraint(condition=models.Q(('phone__regex', '^9[678][0-9]{8}$')), name='enquiry_phone_format'),
        ),
        migrations.AddConstraint(
            model_name='enquiry',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('NEW', 'CONTACTED', 'FOLLOW_UP', 'INTERESTED'))), fields=('training', 'phone'), name='enquiry_one_open_per_phone_training'),
        ),
        migrations.AddConstraint(
            model_name='enquirynote',
            constraint=models.CheckConstraint(condition=models.Q(('text', ''), _negated=True), name='enquirynote_text_not_blank'),
        ),
    ]
