# Generated by Django 5.2.4 on 2026-10-07 10:09

import apps.common.utils.helpers
import apps.common.validators
import apps.institutes.validators
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=160)),
                ('overview', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('PHYSICAL', 'Physical'), ('ONLINE', 'Online'), ('HYBRID', 'Hybrid')], max_length=10)),
                ('level', models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=15)),
                ('duration_value', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_unit', models.CharField(blank=True, choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months')], max_length=10)),
                ('duration_weeks', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('fee_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seats', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('eligibility', models.TextField(blank=True)),
                ('certification', models.CharField(blank=True, max_length=255)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=25, validators=[apps.common.validators.validate_phone_number])),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('cover_image', models.ImageField(blank=True, upload_to=apps.common.utils.helpers.get_upload_path, validators=[apps.institutes.validators.validate_image_file])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Pending review'), ('APPROVED', 'Approved'), ('CHANGES_REQUESTED', 'Changes requested'), ('REJECTED', 'Rejected'), ('UNPUBLISHED', 'Unpublished'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('review_feedback', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='common.category')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='institutes.institute')),
                ('institute_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='institutes.institutelocation')),
            ],
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=300)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='training.training')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='training.training')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('class_days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SUN', 'Sun'), ('MON', 'Mon'), ('TUE', 'Tue'), ('WED', 'Wed'), ('THU', 'Thu'), ('FRI', 'Fri'), ('SAT', 'Sat')], max_length=3), size=7)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='training.training')),
            ],
            options={
                'ordering': ('start_time', 'pk'),
            },
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(condition=models.Q(('status', 'APPROVED')), fields=['start_date'], name='training_start_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(condition=models.Q(('status', 'APPROVED')), fields=['-published_at'], name='training_published_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['institute', 'status'], name='training_inst_status_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['category', 'status'], name='training_cat_status_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['status', 'end_date'], name='training_status_end_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='training_search_gin'),
        ),
        migrations.AddConstraint(
            model_name='training',
            constraint=models.CheckConstraint(condition=models.Q(('institute_location__isnull', False), ('mode', 'ONLINE'), _negated=True), name='training_online_has_no_location'),
        ),
        migrations.AddConstraint(
            model_name='training',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='training_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='training',
            constraint=models.CheckConstraint(condition=models.Q(('registration_deadline__isnull', True), ('start_date__isnull', True), ('registration_deadline__lte', models.F('start_date')), _connector='OR'), name='training_deadline_before_start'),
        ),
        migrations.AddConstraint(
            model_name='training',
            constraint=models.CheckConstraint(condition=models.Q(('fee_npr__isnull', True), ('fee_npr__gte', 0), _connector='OR'), name='training_fee_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='training',
            constraint=models.CheckConstraint(condition=models.Q(('seats__isnull', True), ('seats__gt', 0), _connector='OR'), name='training_seats_positive'),
        ),
        migrations.AddConstraint(
            model_name='training',
            constraint=models.CheckConstraint(condition=models.Q(('duration_value__isnull', True), ('duration_value__gt', 0), _connector='OR'), name='training_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='training',
            constraint=models.CheckConstraint(condition=models.Q(('duration_value__isnull', True), models.Q(('duration_unit', ''), _negated=True), _connector='OR'), name='training_duration_has_unit'),
        ),
        migrations.AddIndex(
            model_name='learningoutcome',
            index=models.Index(fields=['training', 'position'], name='training_outcome_pos_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingmodule',
            index=models.Index(fields=['training', 'position'], name='training_module_pos_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingsession',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='training_session_ends_after_start'),
        ),
    ]
