# Generated by Django 5.2.4 on 2026-10-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningoutcome',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='trainingmodule',
            options={'ordering': ('pk',)},
        ),
    ]
