# Generated by Django 5.2.4 on 2026-10-07 10:09

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('hue', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='common.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'indexes': [models.Index(fields=['parent', 'is_active'], name='common_category_parent_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('parent'), condition=models.Q(('parent__isnull', False)), name='common_category_name_per_parent_uniq'), models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('parent__isnull', True)), name='common_category_top_level_name_uniq'), models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='common_category_not_its_own_parent'), models.CheckConstraint(condition=models.Q(('hue__isnull', True), ('hue__lte', 360), _connector='OR'), name='common_category_hue_range')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('code', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('PROVINCE', 'Province'), ('DISTRICT', 'District'), ('MUNICIPALITY', 'Municipality')], max_length=12)),
                ('type', models.CharField(blank=True, choices=[('METROPOLITAN', 'Metropolitan city'), ('SUB_METROPOLITAN', 'Sub-metropolitan city'), ('MUNICIPALITY', 'Municipality'), ('RURAL_MUNICIPALITY', 'Rural municipality')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.location')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='common.location')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.location')),
            ],
            options={
                'indexes': [models.Index(fields=['level', 'parent'], name='common_location_level_idx'), models.Index(fields=['province'], name='common_location_province_idx'), models.Index(fields=['district'], name='common_location_district_idx')],
                'constraints': [models.UniqueConstraint(fields=('level', 'code'), name='common_location_level_code_uniq'), models.UniqueConstraint(fields=('parent', 'name'), name='common_location_parent_name_uniq'), models.CheckConstraint(condition=models.Q(models.Q(('district__isnull', True), ('level', 'PROVINCE'), ('parent__isnull', True), ('province__isnull', True)), models.Q(('district__isnull', True), ('level', 'DISTRICT'), ('parent__isnull', False), ('province__isnull', False)), models.Q(('district__isnull', False), ('level', 'MUNICIPALITY'), ('parent__isnull', False), ('province__isnull', False)), _connector='OR'), name='common_location_level_shape')],
            },
        ),
    ]
