# Generated by Django 5.2.4 on 2026-10-01 06:46

import apps.common.validators
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manage_enquiries', 'Can handle enquiries'), ('manage_account_status', 'Can activate/suspend accounts'), ('manage_institutes', 'Can review institutes'), ('manage_trainings', 'Can review trainings'), ('manage_categories', 'Can manage categories and locations'), ('manage_admins', 'Can manage admin users')]},
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super admin'), ('ADMIN', 'Admin'), ('INSTITUTE_STAFF', 'Institute staff')], default='INSTITUTE_STAFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that phone number already exists.'}, max_length=25, null=True, unique=True, validators=[apps.common.validators.validate_phone_number], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='users_user_role_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='users_user_email_ci_unique', violation_error_message='A user with that email already exists.'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_superuser', True), ('role', 'SUPER_ADMIN')), models.Q(models.Q(('role', 'SUPER_ADMIN'), _negated=True), ('is_superuser', False)), _connector='OR'), name='users_user_superuser_matches_role'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_staff', True), ('role__in', ('SUPER_ADMIN', 'ADMIN'))), models.Q(('is_staff', False), ('role', 'INSTITUTE_STAFF')), _connector='OR'), name='users_user_staff_matches_role'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'SUPER_ADMIN')), fields=('role',), name='users_user_single_super_admin', violation_error_message='There can be only one super admin.'),
        ),
    ]
