# Generated by Django 5.2.4 on 2026-10-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistributedAppKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('remarks', models.CharField(help_text='purpose of app_key. eg for Android, IOS', max_length=255)),
            ],
        ),
    ]
