# Generated by Django 5.2.4 on 2026-10-07 10:09

import apps.common.utils.helpers
import apps.common.validators
import apps.institutes.storage
import apps.institutes.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('PRIVATE_TRAINING_AFFILIATED', 'Private Training Affiliated'), ('CTEVT_AFFILIATED', 'CTEVT Affiliated'), ('VOCATIONAL_TRAINING', 'Vocational Training'), ('LANGUAGE_SCHOOL', 'Language School'), ('COMPANY', 'Company'), ('NGO_INGO', 'NGO/INGO'), ('GOVERNMENT', 'Government')], max_length=30)),
                ('established_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to=apps.common.utils.helpers.get_upload_path, validators=[apps.institutes.validators.validate_image_file])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INFO_REQUESTED', 'Info requested'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('status_reason', models.TextField(blank=True)),
                ('ceo_name', models.CharField(blank=True, max_length=150)),
                ('ceo_message', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=25, validators=[apps.common.validators.validate_phone_number])),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='institutes_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='InstituteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('file', models.FileField(storage=apps.institutes.storage.PrivateStorage, upload_to=apps.common.utils.helpers.get_upload_path, validators=[apps.institutes.validators.validate_document_file])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='institutes.institute')),
            ],
            options={
                'indexes': [models.Index(fields=['institute', 'status'], name='institutes_doc_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='InstituteGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=apps.common.utils.helpers.get_upload_path, validators=[apps.institutes.validators.validate_image_file])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='institutes.institute')),
            ],
            options={
                'indexes': [models.Index(fields=['institute', 'position'], name='institutes_gallery_pos_idx')],
            },
        ),
        migrations.CreateModel(
            name='InstituteInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('STAFF', 'Staff')], default='STAFF', max_length=10)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REVOKED', 'Revoked')], default='PENDING', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='institutes.institute')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='institutes_invite_expiry_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('institute'), condition=models.Q(('status', 'PENDING')), name='institutes_one_pending_invite')],
            },
        ),
        migrations.CreateModel(
            name='InstituteLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=255)),
                ('map_url', models.URLField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=25, validators=[apps.common.validators.validate_phone_number])),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='institutes.institute')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.location')),
            ],
            options={
                'indexes': [models.Index(fields=['institute', 'is_active'], name='institutes_loc_active_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_main', True)), fields=('institute',), name='institutes_one_main_location'), models.CheckConstraint(condition=models.Q(('is_active', False), ('is_main', True), _negated=True), name='institutes_main_location_is_active')],
            },
        ),
        migrations.CreateModel(
            name='InstituteMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('STAFF', 'Staff')], max_length=10)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='institutes.institute')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('role', 'OWNER')), fields=('institute',), name='institutes_one_owner_per_institute')],
            },
        ),
    ]
