# Generated by Django 5.2.4 on 2026-10-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutelocation',
            name='map_url',
            field=models.URLField(blank=True),
        ),
    ]
