# Generated by Django 5.2.4 on 2026-10-08 04:02

import apps.common.utils.helpers
import apps.common.validators
import apps.institutes.validators
import django.db.models.deletion
from django.db import migrations, models


def split_profile(apps, schema_editor):
    """Copy the old flat profile columns into the new contact / CEO / social-link tables.

    Runs after the new tables exist and before the old columns are dropped. Uses the
    historical models only, never the real ones.
    """
    Institute = apps.get_model("institutes", "Institute")
    Member = apps.get_model("institutes", "InstituteMember")
    Contact = apps.get_model("institutes", "InstituteContact")
    CEO = apps.get_model("institutes", "InstituteCEO")
    SocialLink = apps.get_model("institutes", "InstituteSocialLink")

    # full_name is nullable, and the contact person is a required column
    owner_names = {
        institute_id: (full_name or "")[:150]
        for institute_id, full_name in Member.objects.filter(role="OWNER").values_list(
            "institute_id", "user__full_name"
        )
    }

    contacts, ceos, links = [], [], []
    for institute in Institute.objects.iterator():
        # every institute gets exactly one contact row, so the contact endpoint never has to create it
        contacts.append(
            Contact(
                institute=institute,
                contact_person=owner_names.get(institute.pk, ""),
                contact_phone=institute.contact_phone,
                contact_email=institute.contact_email,
            )
        )
        if institute.ceo_name:
            ceos.append(
                CEO(
                    institute=institute,
                    name=institute.ceo_name,
                    message=institute.ceo_message,
                )
            )
        for platform, url in (
            ("website", institute.website),
            ("facebook", institute.facebook_url),
            ("linkedin", institute.linkedin_url),
        ):
            if url:
                links.append(SocialLink(institute=institute, platform=platform, url=url))

    Contact.objects.bulk_create(contacts)
    CEO.objects.bulk_create(ceos)
    SocialLink.objects.bulk_create(links)

    if schema_editor.connection.vendor == "postgresql":
        # fire the deferred foreign-key checks now, so the ALTER TABLEs below cannot hit
        # "cannot ALTER TABLE ... because it has pending trigger events"
        schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='registration_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InstituteCEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to=apps.common.utils.helpers.get_upload_path, validators=[apps.institutes.validators.validate_image_file])),
                ('linkedin_url', models.URLField(blank=True)),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ceo', to='institutes.institute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstituteContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('contact_person', models.CharField(max_length=150)),
                ('contact_phone', models.CharField(max_length=25, validators=[apps.common.validators.validate_phone_number])),
                ('contact_email', models.EmailField(max_length=254)),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='institutes.institute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstituteSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'X (Twitter)'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('website', 'Website'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='institutes.institute')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('platform', 'other'), _negated=True), fields=('institute', 'platform'), name='institutes_unique_social_platform')],
            },
        ),
        # copy the data while the old columns still exist, then drop them
        migrations.RunPython(split_profile, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='institute',
            name='ceo_message',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='ceo_name',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='website',
        ),
    ]
