# Generated by Django 5.2.4 on 2026-10-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='registration_number',
            field=models.CharField(default=123456789, max_length=50),
            preserve_default=False,
        ),
    ]
