# Generated by Django 5.2.4 on 2026-10-07 18:05

import apps.common.utils.helpers
import apps.common.validators
import apps.institutes.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0002_institute_registration_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='ceo_message',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='ceo_name',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='website',
        ),
        migrations.CreateModel(
            name='InstituteCEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to=apps.common.utils.helpers.get_upload_path, validators=[apps.institutes.validators.validate_image_file])),
                ('linkedin_url', models.URLField(blank=True)),
                ('institute', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ceo', to='institutes.institute')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('institute',), name='institutes_one_ceo')],
            },
        ),
        migrations.CreateModel(
            name='InstituteContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('contact_person', models.CharField(max_length=150)),
                ('contact_phone', models.CharField(max_length=25, validators=[apps.common.validators.validate_phone_number])),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='institutes.institute')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('institute',), name='institutes_one_contact')],
            },
        ),
        migrations.CreateModel(
            name='InstituteSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'X (Twitter)'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('website', 'Website'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='institutes.institute')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('institute', 'platform'), name='institutes_unique_social_platform')],
            },
        ),
    ]
