# Generated by Django 5.2.4 on 2026-10-02 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('code', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('PROVINCE', 'Province'), ('DISTRICT', 'District'), ('MUNICIPALITY', 'Municipality')], max_length=12)),
                ('type', models.CharField(blank=True, choices=[('METROPOLITAN', 'Metropolitan city'), ('SUB_METROPOLITAN', 'Sub-metropolitan city'), ('RURAL_MUNICIPALITY', 'Rural municipality'), ('MUNICIPALITY', 'Municipality')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.location')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.location')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.location')),
            ],
            options={
                'indexes': [models.Index(fields=['level', 'parent'], name='catalog_location_level_idx'), models.Index(fields=['province'], name='catalog_location_province_idx'), models.Index(fields=['district'], name='catalog_location_district_idx')],
                'constraints': [models.UniqueConstraint(fields=('level', 'code'), name='catalog_location_level_code_uniq'), models.UniqueConstraint(fields=('parent', 'name'), name='catelog_location_parent_name_uniq'), models.CheckConstraint(condition=models.Q(models.Q(('district__isnull', True), ('level', 'PROVINCE'), ('parent__isnull', True), ('province__isnull', True)), models.Q(('district__isnull', True), ('level', 'DISTRICT'), ('parent__isnull', False), ('province__isnull', False)), models.Q(('district__isnull', False), ('level', 'MUNICIPALITY'), ('parent__isnull', False), ('province__isnull', False)), _connector='OR'), name='catelog_location_level_shape')],
            },
        ),
    ]
