# Generated by Django 5.2.4 on 2026-10-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='catelog_location_parent_name_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='location',
            name='catelog_location_level_shape',
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(blank=True, choices=[('METROPOLITAN', 'Metropolitan city'), ('SUB_METROPOLITAN', 'Sub-metropolitan city'), ('MUNICIPALITY', 'Municipality'), ('RURAL_MUNICIPALITY', 'Rural municipality')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='catalog_location_parent_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('district__isnull', True), ('level', 'PROVINCE'), ('parent__isnull', True), ('province__isnull', True)), models.Q(('district__isnull', True), ('level', 'DISTRICT'), ('parent__isnull', False), ('province__isnull', False)), models.Q(('district__isnull', False), ('level', 'MUNICIPALITY'), ('parent__isnull', False), ('province__isnull', False)), _connector='OR'), name='catalog_location_level_shape'),
        ),
    ]
