# Generated by Django 5.2.4 on 2026-10-05 04:39

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_fix_choices_and_constraint_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'indexes': [models.Index(fields=['parent', 'is_active'], name='catalog_category_parent_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('parent'), condition=models.Q(('parent__isnull', False)), name='catalog_category_name_per_parent_uniq'), models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('parent__isnull', True)), name='catalog_category_top_level_name_uniq'), models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='catalog_category_not_its_own_parent')],
            },
        ),
    ]
