# Generated by Django 5.2.4 on 2026-10-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hue',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('hue__isnull', True), ('hue__lte', 360), _connector='OR'), name='catalog_category_hue_range'),
        ),
    ]
